FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY pom.xml ./
COPY .mvn .mvn
COPY src src

RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /workspace/target/sgcmapi-*.jar ./sgcmapi.jar

EXPOSE 9000

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
